-- Snowflake Infrastructure Setup for dbt
-- Run these commands as ACCOUNTADMIN or a user with CREATE DATABASE privileges

-- 1. Create ANALYTICS database for dbt outputs (separate from raw data)
CREATE DATABASE IF NOT EXISTS ANALYTICS;

-- 2. PUBLIC schema is automatically created by Snowflake, but we can ensure it exists
CREATE SCHEMA IF NOT EXISTS ANALYTICS.PUBLIC;

-- 3. Ensure raw data databases exist (may already exist from ETL work)
CREATE DATABASE IF NOT EXISTS AVA;
CREATE DATABASE IF NOT EXISTS CASEWORK;

-- 4. Create dbt transformation role
CREATE ROLE IF NOT EXISTS ROLE_DBT_TRANSFORM;

-- 5. Grant permissions to read from raw data schemas
-- AVA database (chatbot data)
GRANT USAGE ON DATABASE AVA TO ROLE ROLE_DBT_TRANSFORM;
GRANT USAGE ON SCHEMA AVA.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;
GRANT SELECT ON ALL TABLES IN SCHEMA AVA.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AVA.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;

-- CASEWORK database (legal casework data)
GRANT USAGE ON DATABASE CASEWORK TO ROLE ROLE_DBT_TRANSFORM;
GRANT USAGE ON SCHEMA CASEWORK.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;
GRANT SELECT ON ALL TABLES IN SCHEMA CASEWORK.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CASEWORK.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;

-- 6. Grant permissions to write to ANALYTICS database
GRANT USAGE ON DATABASE ANALYTICS TO ROLE ROLE_DBT_TRANSFORM;
GRANT USAGE ON SCHEMA ANALYTICS.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;
GRANT CREATE TABLE ON SCHEMA ANALYTICS.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;
GRANT CREATE VIEW ON SCHEMA ANALYTICS.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;
GRANT ALL PRIVILEGES ON SCHEMA ANALYTICS.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ANALYTICS.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA ANALYTICS.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA ANALYTICS.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA ANALYTICS.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;

-- 7. Grant DBT role to ETL_USER (reusing existing user)
GRANT ROLE ROLE_DBT_TRANSFORM TO USER ETL_USER;

-- 8. Allow Power BI to read analytics outputs
GRANT USAGE ON DATABASE ANALYTICS TO ROLE ROLE_PBI_READ;
GRANT USAGE ON SCHEMA ANALYTICS.PUBLIC TO ROLE ROLE_PBI_READ;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS.PUBLIC TO ROLE ROLE_PBI_READ;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS.PUBLIC TO ROLE ROLE_PBI_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS.PUBLIC TO ROLE ROLE_PBI_READ;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS.PUBLIC TO ROLE ROLE_PBI_READ;

-- Verification queries
SHOW GRANTS TO ROLE ROLE_DBT_TRANSFORM;
SHOW GRANTS TO USER ETL_USER;
SHOW DATABASES;
SHOW SCHEMAS IN DATABASE ANALYTICS;
SHOW SCHEMAS IN DATABASE AVA;
SHOW SCHEMAS IN DATABASE CASEWORK;
