-- Snowflake Infrastructure Setup for dbt
-- Run these commands as ACCOUNTADMIN or a user with CREATE DATABASE privileges

-- 1. Create AVA database if it doesn't exist (may already exist from previous ETL work)
CREATE DATABASE IF NOT EXISTS AVA;

-- 2. Create ANALYTICS schema for dbt outputs
CREATE SCHEMA IF NOT EXISTS AVA.ANALYTICS;

-- 3. Create dbt transformation role
CREATE ROLE IF NOT EXISTS ROLE_DBT_TRANSFORM;

-- 4. Grant permissions to read from raw data schemas
GRANT USAGE ON DATABASE AVA TO ROLE ROLE_DBT_TRANSFORM;
GRANT USAGE ON SCHEMA AVA.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;
GRANT USAGE ON SCHEMA AVA.CASEWORK TO ROLE ROLE_DBT_TRANSFORM;
GRANT SELECT ON ALL TABLES IN SCHEMA AVA.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;
GRANT SELECT ON ALL TABLES IN SCHEMA AVA.CASEWORK TO ROLE ROLE_DBT_TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AVA.PUBLIC TO ROLE ROLE_DBT_TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AVA.CASEWORK TO ROLE ROLE_DBT_TRANSFORM;

-- 5. Grant permissions to write to ANALYTICS schema
GRANT USAGE ON SCHEMA AVA.ANALYTICS TO ROLE ROLE_DBT_TRANSFORM;
GRANT CREATE TABLE ON SCHEMA AVA.ANALYTICS TO ROLE ROLE_DBT_TRANSFORM;
GRANT CREATE VIEW ON SCHEMA AVA.ANALYTICS TO ROLE ROLE_DBT_TRANSFORM;
GRANT ALL PRIVILEGES ON SCHEMA AVA.ANALYTICS TO ROLE ROLE_DBT_TRANSFORM;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA AVA.ANALYTICS TO ROLE ROLE_DBT_TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA AVA.ANALYTICS TO ROLE ROLE_DBT_TRANSFORM;

-- 6. Grant DBT role to ETL_USER (reusing existing user)
GRANT ROLE ROLE_DBT_TRANSFORM TO USER ETL_USER;

-- 7. Allow Power BI to read analytics outputs
GRANT USAGE ON SCHEMA AVA.ANALYTICS TO ROLE ROLE_PBI_READ;
GRANT SELECT ON ALL TABLES IN SCHEMA AVA.ANALYTICS TO ROLE ROLE_PBI_READ;
GRANT SELECT ON ALL VIEWS IN SCHEMA AVA.ANALYTICS TO ROLE ROLE_PBI_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AVA.ANALYTICS TO ROLE ROLE_PBI_READ;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA AVA.ANALYTICS TO ROLE ROLE_PBI_READ;

-- Verification queries
SHOW GRANTS TO ROLE ROLE_DBT_TRANSFORM;
SHOW GRANTS TO USER ETL_USER;
SHOW DATABASES;
SHOW SCHEMAS IN DATABASE AVA;
